### ISSUE TITLE
Idea: Hooks support?

### ISSUE THREAD

**Issue by jakebolam** [tophat/with-immutable-props-to-js#63] opened 2019-06-23 21:23 UTC
## Description
Would be cool to future proof this by adding a `useImmutableProps` hook. I'm not sure if belongs in this library, or another one (maybe this turns into just immutable-props-to-js)

## Rationale
Hooks are getting more traction, and appear to be a better pattern for building scailing react apps.

**Comment by msrose** [comment] 2019-06-23 21:46
Yeah I was thinking about this, but not sure what the API would look like. The whole idea of this HOC is that it operates on the props _before_ they get into the component, and I don't see how hooks can do that. A quick google suggests similar ideas expressed in [this blog post](https://medium.com/@albertchu539/higher-order-components-in-a-react-hooks-world-69fe1f0b0791): prop mutation doesn't make sense with hooks. But if you have an example that shows otherwise I'd for sure be keen :)

**Comment by fang0rnz** [comment] 2019-08-07 17:50
any news on this? not sure on how to proceed using immutalbejs with redux hooks

**Comment by msrose** [comment] 2019-08-12 13:26
Going to close this as Won't Fix for now as I don't believe there is no way to accomplish prop mutation with hooks in a way that succeeds in keeping Immutable.js outside the component. Hooks do not replace all need for HOCs, so it's fine to use this as a HOC as usual. If anyone has a suggestion for a suitable API that succeeds in keeping Immutable.js outside presentational components, please comment on this issue and we'll reopen it.

**Closed by msrose** 2019-08-12 13:26 UTC

**Comment by eric-burel** [comment] 2021-07-05 07:42
Hi, I am working on an old project where I use Immutable massively and I cannot yet switch to more modern approach with Immer.

Regarding hooks, I think it could be as simple as:
```js
// selector is expected to be a selector that return an immutable non primitive object (Map, List...)
const useImmutableSelector = (selector) => {
   const immutableValue =useSelector(selector)
   const value = useMemo(() =>  immutableValue.toJS()
   return value
}
```
It's very similar to doing this:
```js
// this is memoized so "fine": toJS() will only be called if the immutable value is changed
// but it's also tedious
const mySelectorJS = createSelector(mySelectorImmutable, (val) => val.toJS())
```

The main advantage though is that with a hook, you don't need to define a set of JS selectors beforehand in addition to the immutable one, which would lead to a ton of confusion. You keep the selector immutable, and do the conversion in your container, everything at the right place, no code duplication.
Another advantage is that for more complex selector, it's easy to break memoization without noticing: then the selector may be rerun without the immutable values having changed => in this case `toJS()` will be called again. The hook is not sensitive to this, because it always check against the immutable value before converting.

Hooks indeed operate within the component and not before the props get into the component. But that's not a problem: you can still define an container component that calls the hooks and a stateless component that just get the JS value.

Another point:
Current implementation of the library seems wrong to me, because it doesn't cache the converted value.
So, if immutable propA changes, it will call `propA.toJS()`... but also `propB.toJS()` and `propC.toJS()`.

I'll dig that more deeply later on but I think the solution is to maintain some state to remember the previous immutable value, and only convert object that have actually changed.

**Comment by eric-burel** [comment] 2021-07-05 13:58
Sharing the failing test and the fix:
```jsx
// doesn't pass! B is recomputed but should not
import React, { useState } from 'react';
import { render, fireEvent, screen } from '@testing-library/react';
import { fromJS } from 'immutable';
mport withImmutablePropsToJS from 'with-immutable-props-to-js';

describe('withImmutablePropsToJS', () => {
  test('should have two renders when state is updated', async () => {
    const Counter = ({ A, B }) => {
      const [initA] = useState(A);
      const [initB] = useState(B);
      return (
        <div>
          <p>
            {initA === A ? 'A is same' : 'A is not same'}
            {initB === B ? 'B is same' : 'B is not same'}
          </p>
        </div>
      );
    };
    const WithImmutableCounter = withImmutablePropsToJS(Counter);
    const Component = () => {
      const [immutA, setImmutA] = useState(fromJS({}));
      const [immutB /* , setImmutB */] = useState(fromJS({}));
      return (
        <div>
          <button
            type="button"
            onClick={() => {
              console.log('setting immutA');
              setImmutA(fromJS({ foo: 'bar' }));
            }}
          >
            Trigger update A
          </button>
          <WithImmutableCounter A={immutA} B={immutB} />
        </div>
      );
    };
    // const { renderCount } = perf(React);

    render(<Component />);

    fireEvent.click(screen.getByRole('button', { name: /Trigger update A/i }));
    const testParagraph = document.querySelector('p');
    expect(testParagraph).toHaveTextContent(/A is not same/);
    expect(testParagraph).toHaveTextContent(/B is same/);
    // await wait(() => expect(renderCount.current.Counter.value).toBe(2));
  });
});
```
Fix (it's a naive 5 minute work so be careful! it might not work as expected!):
```js
import hoistNonReactStatics from 'hoist-non-react-statics';
import React, { useState, useRef } from 'react';
import { Iterable } from 'immutable';
import PropTypes from 'prop-types';

const getDisplayName = Component => {
  return Component.displayName || Component.name || 'Component';
};

const withImmutablePropsToJS = WrappedComponent => {
  const Wrapper = props => {
    const { forwardedRef, ...rest } = props;
    const [propsJS, setPropsJS] = useState({});
    const previousImmutableProps = useRef({});

    const nextPropsJS = Object.entries(rest).reduce(
      (newProps, [propKey, propValue]) => {
        // it's an immutable object
        const canConvertToJS =
          Iterable.isIterable(propValue) &&
          typeof propValue.toJS === 'function';
        // it has actually changed
        if (previousImmutableProps.current[propKey] !== propValue) {
          // remember this value as the last known props
          previousImmutableProps.current[propKey] = propValue;
          // rerun toJS()
          newProps[propKey] = canConvertToJS ? propValue.toJS() : propValue;
        }
        return newProps;
      },
      {}
    );
    // update state if needed
    if (Object.keys(nextPropsJS).length > 0) {
      setPropsJS(currentProps => ({ ...currentProps, ...nextPropsJS }));
    }
    return <WrappedComponent {...propsJS} ref={forwardedRef} />;
  };

  Wrapper.propTypes = {
    forwardedRef: PropTypes.oneOfType([
      PropTypes.func,
      PropTypes.shape({ current: PropTypes.node })
    ])
  };

  Wrapper.defaultProps = {
    forwardedRef: null
  };

  const WrapperWithForwardedRef = React.forwardRef((props, ref) => (
    <Wrapper {...props} forwardedRef={ref} />
  ));

  WrapperWithForwardedRef.displayName = `withImmutablePropsToJS(${getDisplayName(
    WrappedComponent
  )})`;
  WrapperWithForwardedRef.WrappedComponent = WrappedComponent;

  hoistNonReactStatics(WrapperWithForwardedRef, WrappedComponent);

  return WrapperWithForwardedRef;
};

export default withImmutablePropsToJS;

```

**Comment by msrose** [comment] 2021-07-05 14:29
Hi Eric

The point of this component is not to save calls to .toJS, but to just call it transparently when the component rerenders in order to keep Immutable out of presentational components. I think the memoization you're suggesting is a different optimization that is unnecessary for many apps. Rerendering is much more expensive than a few calls to .toJS.

The hook you suggested is interesting in another sense.
The other idea is to provide a wrapper hook for useSelector that does the conversion if needed, and use that selector everywhere in your app, which is another interesting idea and very close to the hook you wrote but with additional checks for Immutable objects and no useMemo. mapStateToProps gets replaced by container components calling the hook for each prop coming from the Redux state. I think such a hook would have to assume use of Redux, but could nonetheless be handy in some cases.

I still think I'm missing some details as I haven't used Redux with hooks in a real project, so if you have a more detailed example to share it would be much appreciated.

**Comment by eric-burel** [comment] 2021-07-05 14:41
The problem is that the few calls to `.toJS` will actually trigger expensive renders, because you create a new reference object everytime your component is rerendered, and that also includes props that didn't actually change. I don't see a solution without memoization, because you end up with https://github.com/tophat/with-immutable-props-to-js/issues/270, whether using hooks or not.

But I get it that it might be out-of-scope for this package if you only focus on the conversion. The problem is that I certainly trade the `.toJS` conversion for comparisons to a memoized value and thus also consume more memory, so there is a slight tradeoff.

**Comment by msrose** [comment] 2021-07-05 14:54
Yeah so in the case that .toJS is being called on a massive Immutable tree which then gets passed to a large presentational component (like a table for example), you're going to see lots of unnecessary rerenders, and my advice is to not use withImmutablePropsToJs, but pass Immutable objects directly or restructure your component to connect smaller sub-components directly to the Redux state. Moving additional discussion to #270.
